# -*- coding: utf-8 -*-
"""EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txypOdI8HTs__Y92K9hnG6Ee-git3deF
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("data.csv", encoding='latin1')  # or encoding='ISO-8859-1'
df.head()

# Basic info
df.info()

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Drop rows with all missing values
df.dropna(how='all', inplace=True)

# Drop duplicate rows
df.drop_duplicates(inplace=True)

# Shape after cleaning
print("\nShape after cleaning:", df.shape)

# Summary statistics
df.describe()

# Specific statistics
print("Mean Quantity:", df['Quantity'].mean())
print("Median Quantity:", df['Quantity'].median())
print("Mode Quantity:", df['Quantity'].mode()[0])
print("Standard Deviation of Quantity:", df['Quantity'].std())

print("\nMean UnitPrice:", df['UnitPrice'].mean())
print("Median UnitPrice:", df['UnitPrice'].median())
print("Mode UnitPrice:", df['UnitPrice'].mode()[0])
print("Standard Deviation of UnitPrice:", df['UnitPrice'].std())

import matplotlib.pyplot as plt
import seaborn as sns

# Top 10 products
top_products = df['Description'].value_counts().head(10)

plt.figure(figsize=(10,6))
top_products.plot(kind='barh', color='skyblue')
plt.title("Top 10 Selling Products")
plt.xlabel("Number of Purchases")
plt.ylabel("Product Description")
plt.gca().invert_yaxis()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

if 'CustomerID' in df.columns:
    top_customers = df.groupby('CustomerID')['Quantity'].sum().sort_values(ascending=False).head(10)

    plt.figure(figsize=(10,6))
    top_customers.plot(kind='bar', color='orange')
    plt.title("Top 10 Customers by Total Quantity")
    plt.xlabel("Customer ID")
    plt.ylabel("Quantity Purchased")
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.show()

import matplotlib.pyplot as plt

# Step 1: Convert 'InvoiceDate' to datetime (if not already)
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Step 2: Set 'InvoiceDate' as the index
df.set_index('InvoiceDate', inplace=True)

# Step 3: Now you can resample monthly
monthly_sales = df['Quantity'].resample('M').sum()

# Step 4: Plot the monthly trend
plt.figure(figsize=(12,6))
monthly_sales.plot(marker='o', color='green')
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Quantity Sold")
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,5))
sns.heatmap(df.isnull(), cmap='YlOrRd', cbar=False)
plt.title("Missing Values Heatmap")
plt.show()

plt.figure(figsize=(8,5))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

